//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Klijent.AutoServis {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="PodaciAutomobila", Namespace="http://schemas.datacontract.org/2004/07/AutoServis", ItemName="PodatakAutomobila")]
    [System.SerializableAttribute()]
    public class PodaciAutomobila : System.Collections.Generic.List<Klijent.AutoServis.PodatakAutomobila> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PodatakAutomobila", Namespace="http://schemas.datacontract.org/2004/07/AutoServis")]
    [System.SerializableAttribute()]
    public partial class PodatakAutomobila : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double cena_popravkeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_automobilaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_popravkeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string korisnicko_imeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string podaciField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double cena_popravke {
            get {
                return this.cena_popravkeField;
            }
            set {
                if ((this.cena_popravkeField.Equals(value) != true)) {
                    this.cena_popravkeField = value;
                    this.RaisePropertyChanged("cena_popravke");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_automobila {
            get {
                return this.id_automobilaField;
            }
            set {
                if ((this.id_automobilaField.Equals(value) != true)) {
                    this.id_automobilaField = value;
                    this.RaisePropertyChanged("id_automobila");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_popravke {
            get {
                return this.id_popravkeField;
            }
            set {
                if ((this.id_popravkeField.Equals(value) != true)) {
                    this.id_popravkeField = value;
                    this.RaisePropertyChanged("id_popravke");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string korisnicko_ime {
            get {
                return this.korisnicko_imeField;
            }
            set {
                if ((object.ReferenceEquals(this.korisnicko_imeField, value) != true)) {
                    this.korisnicko_imeField = value;
                    this.RaisePropertyChanged("korisnicko_ime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string podaci {
            get {
                return this.podaciField;
            }
            set {
                if ((object.ReferenceEquals(this.podaciField, value) != true)) {
                    this.podaciField = value;
                    this.RaisePropertyChanged("podaci");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AutoServis.ISistem")]
    public interface ISistem {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistem/Korisnik", ReplyAction="http://tempuri.org/ISistem/KorisnikResponse")]
        void Korisnik(string korisnicko_ime, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistem/Automobil", ReplyAction="http://tempuri.org/ISistem/AutomobilResponse")]
        void Automobil(int id_automobila, string podaci, string status, double cena_popravke, string korisnicko_ime, int id_popravke);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistem/Popravka", ReplyAction="http://tempuri.org/ISistem/PopravkaResponse")]
        void Popravka(int id_popravke, string deo, double cena_dela);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistem/brisiAuto", ReplyAction="http://tempuri.org/ISistem/brisiAutoResponse")]
        void brisiAuto(int id_automobila);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistem/brisiKorisnika", ReplyAction="http://tempuri.org/ISistem/brisiKorisnikaResponse")]
        void brisiKorisnika(string korisnicko_ime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistem/brisiPopravke", ReplyAction="http://tempuri.org/ISistem/brisiPopravkeResponse")]
        void brisiPopravke(int id_popravke);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistem/AzuriranjeCene", ReplyAction="http://tempuri.org/ISistem/AzuriranjeCeneResponse")]
        void AzuriranjeCene(string deo, int cena_dela);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistem/UkupniTroskovi", ReplyAction="http://tempuri.org/ISistem/UkupniTroskoviResponse")]
        Klijent.AutoServis.PodaciAutomobila UkupniTroskovi();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistem/LogInAdministrator", ReplyAction="http://tempuri.org/ISistem/LogInAdministratorResponse")]
        bool LogInAdministrator(string korisnicko_ime, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistem/UkupniTroskoviString", ReplyAction="http://tempuri.org/ISistem/UkupniTroskoviStringResponse")]
        string UkupniTroskoviString();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISistemChannel : Klijent.AutoServis.ISistem, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SistemClient : System.ServiceModel.ClientBase<Klijent.AutoServis.ISistem>, Klijent.AutoServis.ISistem {
        
        public SistemClient() {
        }
        
        public SistemClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SistemClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SistemClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SistemClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Korisnik(string korisnicko_ime, string password) {
            base.Channel.Korisnik(korisnicko_ime, password);
        }
        
        public void Automobil(int id_automobila, string podaci, string status, double cena_popravke, string korisnicko_ime, int id_popravke) {
            base.Channel.Automobil(id_automobila, podaci, status, cena_popravke, korisnicko_ime, id_popravke);
        }
        
        public void Popravka(int id_popravke, string deo, double cena_dela) {
            base.Channel.Popravka(id_popravke, deo, cena_dela);
        }
        
        public void brisiAuto(int id_automobila) {
            base.Channel.brisiAuto(id_automobila);
        }
        
        public void brisiKorisnika(string korisnicko_ime) {
            base.Channel.brisiKorisnika(korisnicko_ime);
        }
        
        public void brisiPopravke(int id_popravke) {
            base.Channel.brisiPopravke(id_popravke);
        }
        
        public void AzuriranjeCene(string deo, int cena_dela) {
            base.Channel.AzuriranjeCene(deo, cena_dela);
        }
        
        public Klijent.AutoServis.PodaciAutomobila UkupniTroskovi() {
            return base.Channel.UkupniTroskovi();
        }
        
        public bool LogInAdministrator(string korisnicko_ime, string password) {
            return base.Channel.LogInAdministrator(korisnicko_ime, password);
        }
        
        public string UkupniTroskoviString() {
            return base.Channel.UkupniTroskoviString();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AutoServis.IKlijent")]
    public interface IKlijent {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKlijent/LogInKorisnik", ReplyAction="http://tempuri.org/IKlijent/LogInKorisnikResponse")]
        bool LogInKorisnik(string korisnicko_ime, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKlijent/Uplati", ReplyAction="http://tempuri.org/IKlijent/UplatiResponse")]
        void Uplati(string korisnicko_ime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKlijent/PrikazKorisniku", ReplyAction="http://tempuri.org/IKlijent/PrikazKorisnikuResponse")]
        string PrikazKorisniku(string korisnicko_ime);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKlijentChannel : Klijent.AutoServis.IKlijent, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KlijentClient : System.ServiceModel.ClientBase<Klijent.AutoServis.IKlijent>, Klijent.AutoServis.IKlijent {
        
        public KlijentClient() {
        }
        
        public KlijentClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KlijentClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KlijentClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KlijentClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool LogInKorisnik(string korisnicko_ime, string password) {
            return base.Channel.LogInKorisnik(korisnicko_ime, password);
        }
        
        public void Uplati(string korisnicko_ime) {
            base.Channel.Uplati(korisnicko_ime);
        }
        
        public string PrikazKorisniku(string korisnicko_ime) {
            return base.Channel.PrikazKorisniku(korisnicko_ime);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AutoServis.IOperater")]
    public interface IOperater {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperater/OperaterLogin", ReplyAction="http://tempuri.org/IOperater/OperaterLoginResponse")]
        bool OperaterLogin(string korisnicko_ime, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperater/OperaterAzuriranjeCene", ReplyAction="http://tempuri.org/IOperater/OperaterAzuriranjeCeneResponse")]
        void OperaterAzuriranjeCene(string deo, int cena_dela);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperater/OperaterKorisnik", ReplyAction="http://tempuri.org/IOperater/OperaterKorisnikResponse")]
        void OperaterKorisnik(string korisnicko_ime, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperater/OperaterAutomobil", ReplyAction="http://tempuri.org/IOperater/OperaterAutomobilResponse")]
        void OperaterAutomobil(int id_automobila, string podaci, string status, double cena_popravke, string korisnicko_ime, int id_popravke);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperater/OperaterPopravka", ReplyAction="http://tempuri.org/IOperater/OperaterPopravkaResponse")]
        void OperaterPopravka(int id_popravke, string deo, double cena_dela);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOperaterChannel : Klijent.AutoServis.IOperater, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OperaterClient : System.ServiceModel.ClientBase<Klijent.AutoServis.IOperater>, Klijent.AutoServis.IOperater {
        
        public OperaterClient() {
        }
        
        public OperaterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OperaterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperaterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperaterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool OperaterLogin(string korisnicko_ime, string password) {
            return base.Channel.OperaterLogin(korisnicko_ime, password);
        }
        
        public void OperaterAzuriranjeCene(string deo, int cena_dela) {
            base.Channel.OperaterAzuriranjeCene(deo, cena_dela);
        }
        
        public void OperaterKorisnik(string korisnicko_ime, string password) {
            base.Channel.OperaterKorisnik(korisnicko_ime, password);
        }
        
        public void OperaterAutomobil(int id_automobila, string podaci, string status, double cena_popravke, string korisnicko_ime, int id_popravke) {
            base.Channel.OperaterAutomobil(id_automobila, podaci, status, cena_popravke, korisnicko_ime, id_popravke);
        }
        
        public void OperaterPopravka(int id_popravke, string deo, double cena_dela) {
            base.Channel.OperaterPopravka(id_popravke, deo, cena_dela);
        }
    }
}
